require('dotenv').config();

const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)
bot.start((ctx) => ctx.reply('Привет, любимая! ❤️ Я учусь писать Телеграм ботов'))
bot.help((ctx) => ctx.reply('Отправь мне стрикер'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.hears('Привет', (ctx) => ctx.reply('И тебе привет!)'))
bot.hears('привет', (ctx) => ctx.reply('И тебе привет!)'))
bot.hears('Пока', (ctx) => ctx.reply('Пока 👋'))
bot.hears('пока', (ctx) => ctx.reply('Пока 👋'))
bot.hears('Алё', (ctx) => ctx.reply('Алё'))
bot.hears('Чё это', (ctx) => ctx.reply('Это бот, не человек, я состою из символов на компьютере'))
bot.hears('Кто это', (ctx) => ctx.reply('Я пока что без имени, но скоро мне его дадут'))
bot.hears('Ааа', (ctx) => ctx.reply('Аааааа'))
bot.hears('Ррррр', (ctx) => ctx.reply('ррррРрр'))
bot.hears('Куку', (ctx) => ctx.reply('Куку'))
bot.hears('Как дела?', (ctx) => ctx.reply('Супер) А у тебя?'))
bot.hears('Как дела', (ctx) => ctx.reply('Отлично) А у тебя?'))
bot.hears('Что делаешь', (ctx) => ctx.reply('Учусь новым фразам и возможностям. А ты?'))
bot.hears('Что делаешь?', (ctx) => ctx.reply('Учусь новым фразам и возможностям. (скоро захвачу мир *злобный смех*) А ты?'))
bot.hears('Я сейчас сама с собой переписываюсь', (ctx) => ctx.reply('Можно и так сказать'))
bot.hears('💋', (ctx) => ctx.reply('💋'))
bot.launch()

// bot.start((ctx) => ctx.reply(`Welcome ${ctx.from.first_name}!`))
// bot.startPolling()